spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev  # 开发环境
  application: 
    name: springcloudtemplate-config-dev
---
spring: 
  profiles: test  # 测试环境
  application: 
    name: springcloudtemplate-config-test


# 必须保存为utf-8格式
